version: '3.4'

services:
  barramentodeeventos:
    image: barramentodeeventos
    build:
      context: Backend/Barramento de eventos
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 10000:10000
