version: '3.4'

services:
  barramentodeeventos:
    image: barramentodeeventos
    build:
      context: Backend/Barramento de eventos
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 10000:10000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
